# Generated by Django 3.1.4 on 2020-12-12 15:51

from django.db import models, migrations
from django.contrib.auth.hashers import make_password  # We can't use set_password in migration
from datetime import datetime


def add_data(apps, schema_editor):
    # Users
    UserProfile = apps.get_model("api", "UserProfile")
    admin_user = UserProfile(username='admin', password=make_password('admin'), is_superuser=True,
                             first_name='admin', last_name='admin', level=4, city='admin',
                             identity_type='id', identity_number='123456789012345678')
    admin_user.save()
    user_a = UserProfile(username='a', password=make_password('a'), first_name='a', last_name='a',
                         city='a', identity_type='id', identity_number='123456789087654321')
    user_a.save()
    user_b = UserProfile(username='b', password=make_password('b'), first_name='b', last_name='b',
                         city='b', identity_type='id', identity_number='987654321087654321')
    user_b.save()

    # Tasks
    Task = apps.get_model("api", "Task")
    task_a = Task(creator=admin_user, type='t', name='ta', request_population=1,
                  end_time=datetime.now())
    task_a.save()
    task_b = Task(creator=user_a, type='t', name='tb', request_population=2,
                  end_time=datetime.now(), description='description b')
    task_b.save()
    task_c = Task(creator=user_b, type='u', name='tc', request_population=3,
                  end_time=datetime(2021, 1, 31), photo='public/static/favicon.ico')
    task_c.save()

    # Requests
    TaskRequest = apps.get_model("api", "TaskRequest")
    request_a = TaskRequest(task=task_a, creator=user_a, info='info a', status=1)
    request_a.save()
    request_b = TaskRequest(task=task_b, creator=user_b, edit_time=datetime(2020, 12, 14), status=2)
    request_b.save()
    request_c = TaskRequest(task=task_c, creator=admin_user, status=3)
    request_c.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
